version: '3.3'

networks:
  aw-ec-network:
    driver: bridge

volumes:
  aw-ec-mysql-volume:

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "awmensagens"
    ports:
      - "3306:3306"
    networks:
      - aw-ec-network
    volumes:
      - aw-ec-mysql-volume:/var/lib/mysql
  mensagens-api:
    image: algaworks/algamensagens-api:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "mysql"
    networks:
      - aw-ec-network