spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/aw_user?createDatabaseIfNotExist=true&serverTimezone=UTC
    password:
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update